### ISSUE TITLE
Money is not recovered when you lose

### ISSUE THREAD

**Issue by SteeveDroz** [egordorichev/Server-Defense#1]
Losing once blocks the game, because the money spent is not recovered and you're not rich enough to install your security system, even with wave 1.

Plus, as it is stocked in a cookie, even leaving the application and comming back won't change the problem.

**Comment by egordorichev** [comment]
Thanks for feedback! I probably need to change the economics in my game. Do you think i don't need to store money? I had removed that for now.

**Comment by SteeveDroz** [comment]
I think you can store the money, but not update it if the player loses everything.

Rule of thumb: if you save the money spent, you need to save the elements they bought.

**Comment by egordorichev** [comment]
Thanks! Will do that.
